CREATE TABLE IF NOT EXISTS DIM_PATIENT (
  AGE DOUBLE,
  DATA_SHARING_OPT_IN BOOLEAN, 
  DATE_OF_BIRTH DATE,
  DECEASED_DATE INT REFERENCES DIM_DATE(DATE_ID),
  DECEASED_FLAG BOOLEAN,
  FIRST_NAME STRING,
  FULL_NAME STRING,
  GENDER STRING,
  IS_ACTIVE BOOLEAN,
  LAST_NAME STRING,
  MARITAL_STATUS STRING,
  MIDDLE_NAME STRING,
  PATIENT_ID INT PRIMARY KEY,
  RACE STRING
) COMMENT='Dim table, describe patient';

CREATE TABLE IF NOT EXISTS DIM_CONTACT (
  CONTACT_ID INT PRIMARY KEY,
  CONTACT STRING, 
  CONTACT_TYPE STRING
) COMMENT='Dim table, describe contact';

CREATE TABLE IF NOT EXISTS DIM_PROVIDER (
  AGE FLOAT,
  DATE_OF_BIRTH DATE,
  DECEASED_DATE INT REFERENCES DIM_DATE(DATE_ID),
  DECEASED_FLAG BOOLEAN,
  FIRST_NAME STRING,
  FULL_NAME STRING,
  GENDER STRING,
  IS_ACTIVE BOOLEAN,
  LAST_NAME STRING,
  MIDDLE_NAME STRING,
  PROVIDER_ID INT PRIMARY KEY,
  RACE STRING 
) COMMENT='Dim table, describe provider';

CREATE TABLE IF NOT EXISTS DIM_PROVIDER_SPECIALTY (
  IS_ACTIVE BOOLEAN,
  PROVIDER_SPECIALTY_ID INT PRIMARY KEY,
  SPECIALTY_NAME STRING,
  TAXONOMY_CODE STRING
) COMMENT='Dim table, describe provider specialties';


CREATE TABLE IF NOT EXISTS DIM_LANGUAGE (
  LANGUAGE_ID INT PRIMARY KEY,
  LANGUAGE_NAME STRING,
  ISO_CODE STRING
) COMMENT='Dim table, describe languages';

CREATE TABLE IF NOT EXISTS DIM_LOCATION (
  ADDRESS_TYPE STRING,
  ADDRESS_LINE STRING,
  CITY STRING,
  COUNTRY STRING,
  LOCATION_ID INT PRIMARY KEY,
  STATE_CODE STRING,
  ZIP_CODE STRING
) COMMENT='Dim table, describe location';

CREATE TABLE IF NOT EXISTS DIM_PROCEDURE_TYPE (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  NAME STRING,
  PROCEDURE_TYPE_ID INT PRIMARY KEY
) COMMENT='Dim table, describe procedure events';

CREATE TABLE IF NOT EXISTS DIM_ENROLLMENTS (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  ENROLLMENT_ID INT PRIMARY KEY,
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_ACTIVE BOOLEAN
) COMMENT='Dim table, describe enrollment events';

CREATE TABLE IF NOT EXISTS DIM_PAYMENT_TYPE (
  PAYMENT_TYPE_ID INT PRIMARY KEY,
  PAYMENT_DESCRIPTION STRING,
  PAYMENT_TYPE STRING
) COMMENT='Dim table, describe payment event';

CREATE TABLE IF NOT EXISTS DIM_SURVEYS (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  SCORE INT,
  SURVEY_COMMENTS STRING,
  SURVEY_ID INT PRIMARY KEY
) COMMENT='Dim table, describe survey event ... 1 (worst) to 10 (best)';

CREATE TABLE IF NOT EXISTS DIM_OUTCOME (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  OUTCOME STRING,
  OUTCOME_ID INT PRIMARY KEY
) COMMENT='Dim table, describe outcomes patient appointment outcomes';

CREATE TABLE DIM_DATE (
  DATE_ID INT PRIMARY KEY,  -- e.g., 20240706
  FULL_DATE DATE,
  DAY_OF_WEEK STRING,
  MONTH_NAME STRING,
  QUARTER INT,
  YEAR INT,
  IS_WEEKEND BOOLEAN
) COMMENT='Dim table, describe date';

CREATE TABLE DIM_ENCOUNTER_TYPE (
  ENCOUNTER_TYPE_ID INT PRIMARY KEY,
  ENCOUNTER_TYPE_NAME STRING,
  DESCRIPTION STRING
) COMMENT='Dim table, describe encounter type';