CREATE TABLE IF NOT EXISTS BRIDGE_PATIENT_CONTACT (
  CONTACT_ID INT REFERENCES DIM_CONTACT(CONTACT_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,  
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID), 
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  UNIQUE(PATIENT_ID, CONTACT_ID, EFFECTIVE_DATE)
) COMMENT='Bridge table, linking patient to multiple contacts';

CREATE TABLE IF NOT EXISTS BRIDGE_PROVIDER_CONTACT (
  CONTACT_ID INT REFERENCES DIM_CONTACT(CONTACT_ID),
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,  
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID),
  UNIQUE(PROVIDER_ID, CONTACT_ID, EFFECTIVE_DATE)
) COMMENT='Bridge table, linking provider to multiple contacts';

CREATE TABLE IF NOT EXISTS BRIDGE_PROVIDER_SPECIALTY (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,  
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID), 
  SPECIALTY_ID INT REFERENCES DIM_PROVIDER_SPECIALTY(SPECIALTY_ID),
  UNIQUE(PROVIDER_ID, SPECIALTY_ID, EFFECTIVE_DATE)
) COMMENT='Bridge table, linking provider to multiple provider specialty';

CREATE TABLE IF NOT EXISTS BRIDGE_PROVIDER_LANGUAGE (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,
  LANGUAGE_ID INT REFERENCES DIM_LANGUAGE(LANGUAGE_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID),
  UNIQUE(PROVIDER_ID, LANGUAGE_ID, EFFECTIVE_DATE)
) COMMENT='bridge table, linking provider to multiple provider languages';

CREATE TABLE IF NOT EXISTS BRIDGE_PATIENT_LANGUAGE (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,
  LANGUAGE_ID INT REFERENCES DIM_LANGUAGE(LANGUAGE_ID),
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  UNIQUE(PATIENT_ID, LANGUAGE_ID, EFFECTIVE_DATE)
) COMMENT='bridge table, linking patient to multiple patient languages';

CREATE TABLE IF NOT EXISTS BRIDGE_PATIENT_LOCATION (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,
  LOCATION_ID INT REFERENCES DIM_LOCATION(LOCATION_ID),
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  UNIQUE(PATIENT_ID, LOCATION_ID, EFFECTIVE_DATE)
) COMMENT='bridge table, linking patient to multiple patient locations';

CREATE TABLE IF NOT EXISTS BRIDGE_PROVIDER_LOCATION (
  EFFECTIVE_DATE INT REFERENCES DIM_DATE(DATE_ID),
  EXPIRATION_DATE INT REFERENCES DIM_DATE(DATE_ID),
  IS_CURRENT BOOLEAN,
  IS_PRIMARY BOOLEAN,
  LOCATION_ID INT REFERENCES DIM_LOCATION(LOCATION_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID),
  UNIQUE(PROVIDER_ID, LOCATION_ID, EFFECTIVE_DATE)
) COMMENT='bridge table, linking provider to multiple provider locations';
