CREATE OR REPLACE ROLE DATA_ENGINEER COMMENT = 'Data engineer role';

GRANT USAGE ON DATABASE HEALTH_TECH TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.PROD TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.STAGE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.DEV TO ROLE DATA_ENGINEER;

GRANT SELECT ON TABLE ANALYTICS_MART TO ROLE DATA_ENGINEER;