CREATE OR REPLACE ROLE DATA_SCIENTIST COMMENT = 'Data scientist role';

GRANT USAGE ON DATABASE HEALTH_TECH TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA HEALTH_TECH.PROD TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA HEALTH_TECH.STAGE TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA HEALTH_TECH.DEV TO ROLE DATA_SCIENTIST;

GRANT SELECT ON TABLE ANALYTICS_MART TO ROLE DATA_SCIENTIST;