CREATE OR REPLACE ROLE ML_ENGINEER COMMENT = 'ML engineer role';

GRANT USAGE ON DATABASE HEALTH_TECH TO ROLE ML_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.PROD TO ROLE ML_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.STAGE TO ROLE ML_ENGINEER;
GRANT USAGE ON SCHEMA HEALTH_TECH.DEV TO ROLE ML_ENGINEER;

GRANT SELECT ON TABLE ML_MART TO ROLE ML_ENGINEER;