-- model events galaxy model
-- Clinical Operations
CREATE TABLE IF NOT EXISTS FACT_CLAIMS (
  ALLOWED_AMOUNT DECIMAL(20, 2),
  COINSURANCE_AMOUNT DECIMAL(20, 2),
  CLAIM_ID INT, -- BUSINESS KEY
  DATE_OF_SERVICE INT REFERENCES DIM_DATE(DATE_ID),
  DEDUCTIBLE_AMOUNT DECIMAL(20, 2),
  ID INT AUTOINCREMENT PRIMARY KEY, -- SURROGATE KEY
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID), 
  PAID_AMOUNT DECIMAL(20, 2),
  PAID_DATE INT REFERENCES DIM_DATE(DATE_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID)
) COMMENT='Fact table, track submitted, approved, denied, and paid claims';

CREATE TABLE IF NOT EXISTS FACT_ENCOUNTERS (
  ENCOUNTER_TYPE_ID INT REFERENCES DIM_ENCOUNTER_TYPE(ENCOUNTER_TYPE_ID),
  EVENT_DATE INT REFERENCES DIM_DATE(DATE_ID),
  ID INT AUTOINCREMENT PRIMARY KEY, -- SURROGATE KEY
  OUTCOME_ID INT REFERENCES DIM_OUTCOME(OUTCOME_ID),
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID)
) COMMENT='Fact table, track patient encounters with health coach (over phone)';

CREATE TABLE IF NOT EXISTS FACT_APPOINTMENTS (
  APPOINTMENT_DATE_ID INT REFERENCES DIM_DATE(DATE_ID),
  ID INT AUTOINCREMENT PRIMARY KEY,
  OUTCOME_ID INT REFERENCES DIM_OUTCOME(OUTCOME_ID),
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID),
  GLUCOSE DOUBLE,
  BILIRUBIN DOUBLE,
  ASPARTATE_TRANSAMINASE DOUBLE
) COMMENT='Fact table, track scheduled and completed appointments, cancellations, no-shows';

CREATE TABLE IF NOT EXISTS FACT_LAB_RESULTS (
  ID INT AUTOINCREMENT PRIMARY KEY,
  OUTCOME_ID INT REFERENCES DIM_OUTCOME(OUTCOME_ID),
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  LAB_RESULT_DATE_ID INT REFERENCES DIM_DATE(DATE_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID)
) COMMENT='Fact table, track lab results';

CREATE TABLE IF NOT EXISTS FACT_PROCEDURES (
  ID INT AUTOINCREMENT PRIMARY KEY,
  OUTCOME_ID INT REFERENCES DIM_OUTCOME(OUTCOME_ID), 
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  PROCEDURE_DATE_ID INT REFERENCES DIM_DATE(DATE_ID),
  PROCEDURE_TYPE_ID INT REFERENCES DIM_PROCEDURE_TYPE(PROCEDURE_TYPE_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID)
) COMMENT='Fact table, track completed and scheduled procedures';

-- Marketing & Operations
CREATE TABLE IF NOT EXISTS FACT_ENROLLMENTS (
  ID INT AUTOINCREMENT PRIMARY KEY,
  PATIENT_ID INT REFERENCES DIM_PATIENT(PATIENT_ID),
  ENROLLMENTS_DATE_ID INT REFERENCES DIM_DATE(DATE_ID)
) COMMENT='Fact table, track completed enrollment into health coach program';

-- Finance
CREATE TABLE IF NOT EXISTS FACT_PAYMENTS (
  AMOUNT DECIMAL(20, 2),
  ID INT AUTOINCREMENT PRIMARY KEY,
  OUTCOME_ID INT,
  PATIENT_ID INT,
  PAYMENT_DATE_ID INT REFERENCES DIM_DATE(DATE_ID),
  PAYMENT_TYPE_ID INT REFERENCES DIM_PAYMENT_TYPE(PAYMENT_TYPE_ID)
) COMMENT='Fact table, track payments (insurance or patient)';

-- HR
CREATE TABLE IF NOT EXISTS FACT_EMPLOYEE_SATISFACTION_RESULTS (
  ID INT AUTOINCREMENT PRIMARY KEY,
  OUTCOME_ID INT REFERENCES DIM_OUTCOME(OUTCOME_ID),
  PROVIDER_ID INT REFERENCES DIM_PROVIDER(PROVIDER_ID),
  SURVEY_DATE_ID INT REFERENCES DIM_DATE(DATE_ID),
  SURVEY_ID INT REFERENCES DIM_SURVEYS(SURVEY_ID)
) COMMENT='Fact table, track overall employee satisfaction rating per survey';
