CREATE OR REPLACE DYNAMIC TABLE OPERATIONS_MART
  TARGET_LAG = '5 minutes'
  REFRESH_MODE = INCREMENTAL 
  WAREHOUSE = COMPUTE_WH
AS
SELECT
  PROVIDER_ID AS "provider_id",
  SURVEY_ID   AS "survey_id"
FROM FACT_EMPLOYEE_SATISFACTION_RESULTS;