USE DATABASE DATA_ENG_DBT;
USE SCHEMA PUBLIC;
CREATE TABLE IF NOT EXISTS FACT_CLAIMS (
  id INT,
  member_id INT,
  provider_id INT
);

CREATE TABLE IF NOT EXISTS DIM_MEMBER (
  member_id INT,
  name STRING
);

CREATE TABLE IF NOT EXISTS DIM_PROVIDER (
  provider_id INT,
  name STRING
);
