BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'FACT_CLAIMS'
      AND COLUMN_NAME = 'AMOUNT'
      AND TABLE_SCHEMA = CURRENT_SCHEMA()
  ) THEN
    EXECUTE IMMEDIATE $$
      ALTER TABLE FACT_CLAIMS ADD COLUMN AMOUNT STRING;
    $$;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DIM_MEMBER'
      AND COLUMN_NAME = 'BIRTH_DATE'
      AND TABLE_SCHEMA = CURRENT_SCHEMA()
  ) THEN
    EXECUTE IMMEDIATE $$
      ALTER TABLE DIM_MEMBER ADD COLUMN BIRTH_DATE DATE;
    $$;
  END IF;
END;
