name: Deploy Snowflake Structures

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      - name: Set environment-specific database and schema
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=PROD" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "stage" ]]; then
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=STAGE" >> $GITHUB_ENV
          else
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=DEV" >> $GITHUB_ENV
          fi
          
      - name: Decode & write private key to file
        run: |
          echo "$SNOWFLAKE_PRIVATE_KEY" | base64 -d > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

      - name: Configure Snowflake CLI profile
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.my_snowflake]
          account = "$SNOWFLAKE_ACCOUNT"
          user = "$SNOWFLAKE_USER"
          authenticator = "SNOWFLAKE_JWT"
          private_key_path = "/tmp/private_key.pem"
          database = "$SNOWFLAKE_DATABASE"
          schema = "$SNOWFLAKE_SCHEMA"
          role = "$SNOWFLAKE_ROLE"
          warehouse = "$SNOWFLAKE_WAREHOUSE"
          EOF
          chmod 600 ~/.snowflake/config.toml

      - name: Run SQL files against Snowflake
        run: |
          snow connection set-default my_snowflake
          for file in $(ls sql/*.sql | sort); do
            echo "Running $file..."
            snow sql -f "$file"
          done
