name: Deploy Snowflake Structures

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branch: [main, stage]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      - name: Configure Snowflake CLI profile
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          default_connection_name = "default"
          [connections.default]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          EOF
          chmod 600 ~/.snowflake/config.toml

      - name: Run SQL files against Snowflake
        run: |
          for file in $(ls sql/*.sql | sort); do
            echo "Running $file..."
            snow sql -f "$file"
          done  