name: Deploy Snowflake Structures

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_STORAGE_INTEGRATION: S3_INTEGRATION
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli

      - name: Set environment-specific database and schema
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "SNOWFLAKE_STAGE_FACT_CLAIMS=${BRANCH_NAME}_model_fact_claims_stage" >> $GITHUB_ENV
          echo "SNOWFLAKE_PIPE_FACT_CLAIMS=${BRANCH_NAME}_MODEL_CLAIMS_FACT_PIPE" >> $GITHUB_ENV
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "SNOWFLAKE_BUCKET=application-datalake-us-east-1-${{ secrets.PROD_ACCOUNT_ID }}" >> $GITHUB_ENV
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=PROD" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "stage" ]]; then
            echo "SNOWFLAKE_BUCKET=application-datalake-us-east-1-${{ secrets.STAGE_ACCOUNT_ID }}" >> $GITHUB_ENV
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=STAGE" >> $GITHUB_ENV
          else
            echo "SNOWFLAKE_BUCKET=application-datalake-us-east-1-${{ secrets.DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
            echo "SNOWFLAKE_DATABASE=HEALTH_TECH" >> $GITHUB_ENV
            echo "SNOWFLAKE_SCHEMA=DEV" >> $GITHUB_ENV
          fi
          
      - name: Decode & write private key to file
        run: |
          echo "$SNOWFLAKE_PRIVATE_KEY" | base64 -d > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

      - name: Configure Snowflake CLI profile
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.my_snowflake]
          account = "$SNOWFLAKE_ACCOUNT"
          user = "$SNOWFLAKE_USER"
          authenticator = "SNOWFLAKE_JWT"
          private_key_path = "/tmp/private_key.pem"
          database = "$SNOWFLAKE_DATABASE"
          schema = "$SNOWFLAKE_SCHEMA"
          role = "$SNOWFLAKE_ROLE"
          warehouse = "$SNOWFLAKE_WAREHOUSE"
          EOF
          chmod 600 ~/.snowflake/config.toml

      - name: Deploy data warehouse galaxy model
        run: |
          snow connection set-default my_snowflake
          for file in $(ls data_warehouse_stack/data_warehouse_data_model/*.sql | sort); do
            echo "Running $file..."
            snow sql -f "$file"
          done 

      - name: Deploy data mart(s)
        run: |
          snow connection set-default my_snowflake
          for file in $(ls data_warehouse_stack/data_mart/*.sql | sort); do
            echo "Running $file..."
            snow sql -f "$file"
          done 

      - name: Deploy roles
        run: |
          snow connection set-default my_snowflake
          for file in $(ls data_warehouse_stack/role_permissions/*.sql | sort); do
            echo "Running $file..."
            snow sql -f "$file"
          done 

      - name: Deploy external stage .. storage integration
        run: |
          snow connection set-default my_snowflake
          SNOWFLAKE_STAGE_FACT_CLAIMS_URL=s3://${SNOWFLAKE_BUCKET}/claims/model/fact/
          snow sql -q "CREATE OR REPLACE STAGE ${SNOWFLAKE_STAGE_FACT_CLAIMS} URL = '${SNOWFLAKE_STAGE_FACT_CLAIMS_URL}' STORAGE_INTEGRATION = ${SNOWFLAKE_STORAGE_INTEGRATION}"
    
      - name: Declare snowpipe for data model
        run: |
          snow connection set-default my_snowflake
          snow sql -q "CREATE OR REPLACE PIPE ${SNOWFLAKE_PIPE_FACT_CLAIMS} AUTO_INGEST = FALSE AS COPY INTO FACT_CLAIMS FROM @${SNOWFLAKE_STAGE_FACT_CLAIMS} FILE_FORMAT = (TYPE = 'PARQUET') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE"
